#!/bin/bash

set -ue -o pipefail

# Updates, upgrades, and and cleans homebrew

/usr/local/bin/brew cleanup
/usr/local/bin/brew update
/usr/local/bin/brew upgrade
/usr/local/bin/brew cleanup

# Brew doesn't support any cask update, so uninstall->reinstall
# Props to http://stackoverflow.com/questions/31968664/upgrade-all-the-casks-installed-via-homebrew-cask
/usr/local/bin/brew cask cleanup
casks=($(/usr/local/bin/brew cask list))
for cask in ${casks[@]}
do
	current=$(/usr/local/bin/brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
	if [ -z $(find "/usr/local/Caskroom/$cask" -type d -maxdepth 1 -maxdepth 1 -name "$current") ];
	then
		/usr/local/bin/brew cask uninstall $cask --force
		/usr/local/bin/brew cask install $cask --force
	fi
done
/usr/local/bin/brew cask cleanup

set +ue +o pipefail
